// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMarketPriceHistory = `-- name: GetMarketPriceHistory :many
/**
 * @description
 * This file contains all the SQL queries for interacting with the 'market_price_history' table.
 * These queries are used by sqlc to generate type-safe Go code for our database access layer.
 */

SELECT 
  time,
  market_id,
  open,
  high,
  low,
  close,
  volume,
  resolution
FROM market_price_history
WHERE market_id = $1
  AND time >= $2
  AND time <= $3
  AND resolution = $4
ORDER BY time ASC
`

type GetMarketPriceHistoryParams struct {
	MarketID   string             `json:"market_id"`
	Time       pgtype.Timestamptz `json:"time"`
	Time_2     pgtype.Timestamptz `json:"time_2"`
	Resolution string             `json:"resolution"`
}

// @description Retrieves historical OHLCV data for a given market within a time range and resolution.
// The data is ordered by time ascending and filtered by resolution.
// @param market_id The market ID to fetch data for.
// @param from_time The start time (inclusive) for the query.
// @param to_time The end time (inclusive) for the query.
// @param resolution The resolution/interval (e.g., '1', '5', '15', '60', 'D').
func (q *Queries) GetMarketPriceHistory(ctx context.Context, arg GetMarketPriceHistoryParams) ([]MarketPriceHistory, error) {
	rows, err := q.db.Query(ctx, getMarketPriceHistory,
		arg.MarketID,
		arg.Time,
		arg.Time_2,
		arg.Resolution,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketPriceHistory{}
	for rows.Next() {
		var i MarketPriceHistory
		if err := rows.Scan(
			&i.Time,
			&i.MarketID,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMarketPriceHistory = `-- name: InsertMarketPriceHistory :exec
SELECT insert_market_price_history($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertMarketPriceHistoryParams struct {
	PTime       pgtype.Timestamptz `json:"p_time"`
	PMarketID   string             `json:"p_market_id"`
	POpen       pgtype.Numeric     `json:"p_open"`
	PHigh       pgtype.Numeric     `json:"p_high"`
	PLow        pgtype.Numeric     `json:"p_low"`
	PClose      pgtype.Numeric     `json:"p_close"`
	PVolume     pgtype.Numeric     `json:"p_volume"`
	PResolution string             `json:"p_resolution"`
}

// @description Inserts a new OHLCV bar into the market_price_history table.
// This uses the insert_market_price_history() function which automatically creates partitions.
// @param time The timestamp for this bar.
// @param market_id The market ID.
// @param open The opening price.
// @param high The highest price in the period.
// @param low The lowest price in the period.
// @param close The closing price.
// @param volume The trading volume.
// @param resolution The resolution/interval (e.g., '1', '5', '15', '60', 'D').
func (q *Queries) InsertMarketPriceHistory(ctx context.Context, arg InsertMarketPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, insertMarketPriceHistory,
		arg.PTime,
		arg.PMarketID,
		arg.POpen,
		arg.PHigh,
		arg.PLow,
		arg.PClose,
		arg.PVolume,
		arg.PResolution,
	)
	return err
}
