// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MarketPriceHistory struct {
	Time       pgtype.Timestamptz `json:"time"`
	MarketID   string             `json:"market_id"`
	Open       pgtype.Numeric     `json:"open"`
	High       pgtype.Numeric     `json:"high"`
	Low        pgtype.Numeric     `json:"low"`
	Close      pgtype.Numeric     `json:"close"`
	Volume     pgtype.Numeric     `json:"volume"`
	Resolution string             `json:"resolution"`
}

type MarketPriceHistoryY2025m11 struct {
	Time       pgtype.Timestamptz `json:"time"`
	MarketID   string             `json:"market_id"`
	Open       pgtype.Numeric     `json:"open"`
	High       pgtype.Numeric     `json:"high"`
	Low        pgtype.Numeric     `json:"low"`
	Close      pgtype.Numeric     `json:"close"`
	Volume     pgtype.Numeric     `json:"volume"`
	Resolution string             `json:"resolution"`
}

type MarketPriceHistoryY2025m12 struct {
	Time       pgtype.Timestamptz `json:"time"`
	MarketID   string             `json:"market_id"`
	Open       pgtype.Numeric     `json:"open"`
	High       pgtype.Numeric     `json:"high"`
	Low        pgtype.Numeric     `json:"low"`
	Close      pgtype.Numeric     `json:"close"`
	Volume     pgtype.Numeric     `json:"volume"`
	Resolution string             `json:"resolution"`
}

type MarketSentimentHistory struct {
	Time           pgtype.Timestamptz `json:"time"`
	MarketID       string             `json:"market_id"`
	SentimentScore float64            `json:"sentiment_score"`
	KeyDrivers     []string           `json:"key_drivers"`
}

type MarketSentimentHistoryY2025m11 struct {
	Time           pgtype.Timestamptz `json:"time"`
	MarketID       string             `json:"market_id"`
	SentimentScore float64            `json:"sentiment_score"`
	KeyDrivers     []string           `json:"key_drivers"`
}

type MarketSentimentHistoryY2025m12 struct {
	Time           pgtype.Timestamptz `json:"time"`
	MarketID       string             `json:"market_id"`
	SentimentScore float64            `json:"sentiment_score"`
	KeyDrivers     []string           `json:"key_drivers"`
}

type NewsEvent struct {
	ID          pgtype.UUID        `json:"id"`
	MarketID    string             `json:"market_id"`
	Url         string             `json:"url"`
	Title       string             `json:"title"`
	Source      string             `json:"source"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	MarketID          string             `json:"market_id"`
	TokenID           string             `json:"token_id"`
	PolymarketOrderID pgtype.Text        `json:"polymarket_order_id"`
	Side              string             `json:"side"`
	Size              pgtype.Numeric     `json:"size"`
	Price             pgtype.Numeric     `json:"price"`
	Status            string             `json:"status"`
	SignedOrder       []byte             `json:"signed_order"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	FilledAt          pgtype.Timestamptz `json:"filled_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Trade struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	MarketID          string             `json:"market_id"`
	PolymarketTradeID pgtype.Text        `json:"polymarket_trade_id"`
	Side              string             `json:"side"`
	Size              pgtype.Numeric     `json:"size"`
	Price             pgtype.Numeric     `json:"price"`
	ExecutedAt        pgtype.Timestamptz `json:"executed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	ClerkUserID string             `json:"clerk_user_id"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID                      pgtype.UUID        `json:"id"`
	UserID                  pgtype.UUID        `json:"user_id"`
	PolymarketFunderAddress string             `json:"polymarket_funder_address"`
	SignerSecretRef         string             `json:"signer_secret_ref"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
