// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	GetActiveWalletByUserID(ctx context.Context, userID pgtype.UUID) (Wallet, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
}

var _ Querier = (*Queries)(nil)

