// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
/**
 * @description
 * This file contains all the SQL queries for interacting with the 'users' table.
 * These queries are used by sqlc to generate type-safe Go code for our database access layer.
 */

INSERT INTO users (
  clerk_user_id,
  email
) VALUES (
  $1, $2
)
RETURNING id, clerk_user_id, email, created_at, updated_at
`

type CreateUserParams struct {
	ClerkUserID string `json:"clerk_user_id"`
	Email       string `json:"email"`
}

// @description Creates a new user in the database.
// This is typically called after a 'user.created' webhook event from Clerk.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ClerkUserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, created_at, updated_at FROM users
WHERE clerk_user_id = $1
LIMIT 1
`

// @description Retrieves a single user from the database based on their unique Clerk User ID.
// This will be used frequently in authentication middleware to identify the requesting user.
func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
