// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
/**
 * @description
 * This file contains all the SQL queries for interacting with the 'wallets' table.
 * These queries are used by sqlc to generate type-safe Go code for our database access layer.
 */

INSERT INTO wallets (
  user_id,
  polymarket_funder_address,
  signer_secret_ref
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, polymarket_funder_address, signer_secret_ref, is_active, created_at, updated_at
`

type CreateWalletParams struct {
	UserID                  pgtype.UUID `json:"user_id"`
	PolymarketFunderAddress string      `json:"polymarket_funder_address"`
	SignerSecretRef         string      `json:"signer_secret_ref"`
}

// @description Associates a new Polymarket funder address with a user.
func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.UserID, arg.PolymarketFunderAddress, arg.SignerSecretRef)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolymarketFunderAddress,
		&i.SignerSecretRef,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWalletByUserID = `-- name: GetActiveWalletByUserID :one
SELECT id, user_id, polymarket_funder_address, signer_secret_ref, is_active, created_at, updated_at FROM wallets
WHERE user_id = $1 AND is_active = TRUE
LIMIT 1
`

// @description Retrieves the active wallet for a given user.
// This is used to fetch the signer_secret_ref needed for transaction signing.
func (q *Queries) GetActiveWalletByUserID(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getActiveWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolymarketFunderAddress,
		&i.SignerSecretRef,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
